### ISSUE TITLE
StackExchange OpenID login broken

### ISSUE THREAD

**Issue by donpdonp** [cweiske/indieauth-openid#1]
I hope this is the right repo to report this. OpenID Logins on stack exchange used to work with IndieAuth, but are currently broken.

I was trying to login to
https://askubuntu.com/users/login

and after the indieauth dance finished and returned to the site, the site says
"Message signature was incorrect."

I'm fairly sure this used to work.

**Comment by cweiske** [comment]
Erm, this is not about indieauth.com.
