### ISSUE TITLE
Put data under /tmp or some env variable

### ISSUE THREAD

**Issue by strk** [cweiske/indieauth-openid#2]
By default data could go in `/tmp/<REQUEST_URI>` to allow turnkey deploys by just cloning the repo in a 'indieauth/' directory of your own website. What would you think about that ?

**Comment by cweiske** [comment]
as already discussed on IRC:
- the www directory is there and will stay, so simply checking out into a directory does not work.
- three ways to use it after cloning the git repo somewhere (/usr/local/src or /var/www):
 1. add virtual host to your web server and set its document root to www/
 1. add an alias to an existing vhost and link it to www/
 1. create a symlink in your vhost document root pointing to www/

But it makes sense to move dynamic data out if the static code directories. A config option for the sqlite file path would help here. ENV variables are a bit hard to manage, so I opt for a optional config file.

**Comment by cweiske** [comment]
Implemented, see readme.
